import Layout from "@/components/layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/artMe.png";
import AnimatedText from "@/components/animatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/icons";
import HireMe from "@/components/hireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TypeWriterText from "@/components/typeWriterText";
import TransitionPageEffect from "@/components/transitionPageEffect";


export default function Home() {
  return (
    <>
      {/* add the head html section */}
      <Head>
        <title>3imad</title>
        <meta name="description" content="Generated by create next app" />
      </Head>


      {/* The page transition effect */}
      <TransitionPageEffect />

      {/* the main app */}
      <main className="flex items-center w-full min-h-screen dark:text-light text-dark">
        {/* add the landing page as a compenent from "components/layout" */}
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            {/* add my photo */}
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt="Imad eddine fillali"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw,
                        (max-width: 1200px) 50vw,
                        50vw"
              />
            </div>

            {/* add the description and the title */}
            <div className="flex flex-col items-center self-center w-1/2 lg:w-full lg:text-center">
              {/* use animated text in the title with motion framer */}
              <AnimatedText
                text="Turning Design Into Reality."
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />

              {/* typewriter animation text */}
              <TypeWriterText
                className="w-full my-3 text-left lg:w-full lg:!text-center xl:!text-3xl md:!text-2xl sm:!text-xl xs:!text-lg"
                name="<"
              />

              {/* the description */}
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>

              {/* add the resume & email buttons */}
              <div className="flex items-center self-start mt-2 lg:self-center md:mt-6 sm:mt-7">
                {/* Resume */}
                <Link
                  href="/dummy.pdf"
                  target={"_blank"}
                  className="flex items-center dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light bg-dark text-light p-2.5 px-6 transition-all rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark md:p-2 md:px-4 md:text-base"
                  download={true}>
                  Resume
                  <LinkArrow className={"w-6 ml-1"} />
                </Link>
                {/* Contact */}
                <Link
                  href="mailto:imadeddinefillalipro@gmail.com"
                  target={"_blank"}
                  className="ml-8 text-lg font-medium underline capitalize dark:text-light text-dark md:text-base">
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>

        {/* add hire me button  */}
        <HireMe />

        {/* add the lamp  */}
        <div className="absolute inline-block w-24 right-8 bottom-8 lg:w-20 md:hidden">
          <Image
            src={lightBulb}
            alt="3imad"
            className="w-full h-auto hover:scale-110 duration-300 cursor-pointer"
          />
        </div>
      </main>
    </>
  );
}
